# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Serenity Games
email: admin@serenitygames.net
description: > # this means to ignore newlines until "baseurl:"
    A former Minecraft Server
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serenitygames.net" # the base hostname & protocol for your site
twitter_username: serenitymc
github_username: SerenityGames

# Build settings
markdown: kramdown
strict_front_matter: true
exclude: [.travis.yml, Gemfile, Gemfile.lock, ISSUE_TEMPLATE.md, README.md, CNAME]


defaults:
  - scope:
      type: users
    values:
      layout: user

collections:
  # Serenity_Forum.phpbb_users
  # SQL QUERY USED:
  # select username, user_colour as color, pf_minecraft_ign as ign from phpbb_users LEFT JOIN phpbb_profile_fields_data ON phpbb_users.user_id = phpbb_profile_fields_data.user_id WHERE user_posts > 0 AND user_type != 2 GROUP BY ign
  users:
    output: true
    permalink: /users/:path/
